spring:
  application:
    name: notepadServer

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/notepads_server

  jpa:
    show-sql: true
    hibernate.ddl-auto: create

  main:
    allow-circular-references: true

jwt:
  secret: 'vX601qF6ezEEUj0O64FYgzilt1L61O7Ng2kSxfTMt0qPSJIn0Zy3SfBtg0Hq5vTu'
  lifetime: 1d

server:
  port: 8000

debug: true
